### ISSUE TITLE
Responsive problems 

### ISSUE THREAD

**Issue by Grawl** [HugoGiraudel/sass-guidelines#166] opened 2015-04-11 16:39 UTC
I just visited sass-guidelin.es/ru/ with my iPhone and see that the word “поддерживаемого” and “масштабируемого” in general title is wider than viewport. After this I visited other locales and seen this problem in Chience and Polish. 
<img src="https://cloud.githubusercontent.com/assets/846774/7102235/df84069c-e0b4-11e4-96e9-049465e2083c.jpg" width="40%"> <img src="https://cloud.githubusercontent.com/assets/846774/7102236/dfb460a8-e0b4-11e4-8a85-dd1688ba724d.jpg" width="40%">

**Comment by Grawl** [comment] 2015-04-11 16:41
*Sorry for screenshots. Posting from the same iPhone. *

**Comment by HugoGiraudel** [comment] 2015-04-11 16:42
Indeed. I'll figure something out. Thanks for reporting.

**Comment by HugoGiraudel** [comment] 2015-04-11 20:51
Meh. Cannot reproduce it on my side. :(

**Comment by Grawl** [comment] 2015-04-12 02:49
Okay I just did some research on it and realized that the simplest way to fix this problem with long words is to add `word-wrap: break-word;` to heading selector. But it will not add necessary hyphens in the middle (must be any of `под-дер-жи-ва-е-мо-го` and `мас-шта-би-ру-е-мо-го`).
There is CSS [`hyphens: auto;`](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens) to do exactly this, but it supports Russian hyphenation only in Firefox 8+ and IE 10+.
Instead I suggest to

- use some JS implementation of this feature like [Hyphenator](https://github.com/mnater/Hyphenator)
- or just add some HTML+CSS [like this](http://codepen.io/Grawl/pen/NPZEGg?editors=110) with `&shy;` and `hyphens: auto`

**Comment by Grawl** [comment] 2015-04-12 03:03
Oh I just realized that this feature works just with prefixes: `-webkit-hyphens` and `-moz-hyphens`. No need to `&shy;`.

**Comment by HugoGiraudel** [comment] 2015-04-12 10:54
Fixed with https://github.com/HugoGiraudel/sass-guidelines/commit/e59e218949facbd763ff0efcb7134e89c739e2cd.

**Closed by HugoGiraudel** 2015-04-12 10:54 UTC
